### ISSUE TITLE
[dashboard-request] NHSBoard-ages

### ISSUE THREAD

**Issue by benjbach** [ScottishCovidResponse/rampvis-ui#59]
name of dashboard
* NHS Boadd Data By Age Groups

description of the dashboard
* Different covid data per age groups.

dashboard JS filename
* dashboard-nhsboard-ages.js

specific datastreams to include (which file, which URL, you can link to your spreadsheet if you want)
* https://www.opendata.nhs.scot/dataset/6dbdd466-45e3-4348-9ee3-1eac72b5a592/resource/758f72d6-7371-4eee-9e6b-0b0798470d7e/download/daily_vacc_hb_20210514.csv

**Comment by phongvis** [comment]
I'll work on this next. I suggest to include both age group and sex and it's interesting and the data seems to have both most of the time. 

I see that opendata also has 18 datasets about covid: https://www.opendata.nhs.scot/group/covid-19 and most of them have both sex and age group. I'll start a dashboard with the vaccine data. You can have a look there to see what you find interesting and send me the links (just include the link that shows the table instead of the csv file like https://www.opendata.nhs.scot/dataset/covid-19-in-scotland/resource/19646dce-d830-4ee0-a0a9-fcec79b5ac71 - it's easier for both I think)

**Comment by benjbach** [comment]
OK, I checked, there is no age data for NHS boards unfortunately. So, this dashboard is not very useful, apart for showing vaccination progress. This could better be included into the standard council dashboard I'd say. I will do that and we can remove this (for now).

**Comment by benjbach** [comment]
In fact, that vaccination data by age is already in the dashboardCouncil.js. You can remove this dashboard. I had assumed we can find more age related data (but it seems we only have age data for vaccination)

**Comment by benjbach** [comment]
Closed wrong issue: I just added the vaccination data by age group to the NHS board dashboard.

**Comment by phongvis** [comment]
I found some - actually many, looks like all of the 'wider impacts' datasets have sex & age
- https://www.opendata.nhs.scot/dataset/covid-19-wider-impacts-deaths/resource/733aad2d-5420-4966-bc34-386a3475623f
- https://www.opendata.nhs.scot/dataset/covid-19-wider-impacts-out-of-hours-consultations/resource/ac710637-e7ae-4911-9638-10d9770b2324
- https://www.opendata.nhs.scot/dataset/covid-19-wider-impacts-contacts-with-nhs-24/resource/9bac6060-345e-49ac-a87f-bc700be824aa
- https://www.opendata.nhs.scot/dataset/covid-19-wider-impacts-scottish-ambulance-services/resource/d1d2d098-193f-489c-940a-a828fdcfc357
- https://www.opendata.nhs.scot/dataset/covid-19-wider-impacts-emergency-department-activity/resource/388fd86c-dc0b-4655-b4b1-f13644bfd8d2
